### ISSUE TITLE
Send Metadata less often

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#100]
The metadata currently sends on every request, which is excessive for info that rarely changes. We should throttle it to send less often. The exact meaning of less often can be whatever is easiest to implement. There's no real harm to sending more than needed, but it takes up a fair bit of overhead to constantly be sending data.

In other languages, we send it only when the agent loads (ie, a new Rails or Python worker process boots).

See-also #85

**Comment by asgrim** [comment]
@cschneid my assumption is that this applies to `RegisterMessage` as well as `Metadata`?

**Comment by cschneid** [comment]
Register is required on every socket connect, so unless we cache open socket handles, we have to send Register each time. But it's ok because it doesn't spawn a POST up to our ingest.
