### ISSUE TITLE
Capture requested Query String from URI

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#101]
Python agent: https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/django/middleware.py#L41

We need to capture the requested path and put it in the request tag called `path`.

**Comment by asgrim** [comment]
Note: transferred to `scout-apm-php` since this can be done generically in PHP for all frameworks.

**Comment by asgrim** [comment]
We should also capture query string in the path recorded.

**Comment by asgrim** [comment]
Note: `$_SERVER['REQUEST_URI']` already has the query string, this is already supported.
