### ISSUE TITLE
Unclear error message on invalid Scout log level

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#105]
remote:        [2019-10-23 02:08:27] production.ERROR: Expected the key "warn" to exist. {"exception":"[object] (InvalidArgumentException(code: 0): Expected the key \"warn\" to exist. at /tmp/build_3675d0708815f595c355f5bbcf66d8d8/vendor/webmozart/assert/src/Assert.php:1696)
remote:        [stacktrace]
remote:        #0 /tmp/build_3675d0708815f595c355f5bbcf66d8d8/vendor/webmozart/assert/src/Assert.php(1417): Webmozart\\Assert\\Assert::reportInvalidArgument('Expected the ke...')
remote:        #1 /tmp/build_3675d0708815f595c355f5bbcf66d8d8/vendor/scoutapp/scout-apm-php/src/Logger/FilteredLogLevelDecorator.php(44): Webmozart\\Assert\\Assert::keyExists(Array, 'warn')

**Comment by cschneid** [comment]
I had SCOUT_LOG_LEVEL set to WARN, but that error is super opaque on what's happening.

Also, is 'warn' not a valid log level? or is it the all caps that tripped it up?

**Comment by asgrim** [comment]
Happy to rename the error; but the key should indeed be `warning` not `warn`, see:

https://github.com/php-fig/log/blob/master/Psr/Log/LogLevel.php

These are the standardised log levels in PHP...

**Comment by cschneid** [comment]
It'd be great if we can clarify the error message and give the user a pointer on how to fix it.

**Comment by asgrim** [comment]
Yup, I can definitely do that!
