### ISSUE TITLE
Metadata should have language / language_version fields

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#107]
Standardizing metadata between the various agents - put a fixed "php" string in `language`, and the version (7.3.0 or whatever) in `language_version`

Keep the existing fields for now. Need to ensure that the CoreAgent handles them nicely when missing.

**Comment by asgrim** [comment]
This is already the case:

```php
'language' => 'php',
'version' => PHP_VERSION,
```

Unless I misunderstood something?

**Comment by cschneid** [comment]
The data there is great, this ticket is to standardize the keys between the different agents. Somehow every different scout language agent had this data under different keys making it annoying on the ingestion side of things. 😄 

Simply add `'language_version' => PHP_VERSION` in addition to the existing fields.

**Comment by asgrim** [comment]
Ahh, gotcha :+1: yep, should be simple enough to add.
