### ISSUE TITLE
Autodetect musl environments

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#116]
When the Core Agent is downloaded, we assume libc based linux. But alpine linux is a common docker base, and it uses musl instead. 

We have a build for that, and other language agents attempt to detect musl vs. libc (it's surprisingly difficult to do reliably). We should mirror the other agents and try to detect it here too.

Elixir has the [best approach](https://github.com/scoutapp/scout_apm_elixir/blob/2f8c7b033fd84a9c9e2db0a4797d6e93b6b90bcf/lib/scout_apm/core.ex#L82) afaik, checking for /etc/alpine-release. We've also attempted to execute `ldd` and parse its output, but that fails in some situations too.

**Comment by asgrim** [comment]
I wonder if having a configuration option makes sense here. We could try to access `/etc/alpine-release`, but we can't guarantee we can access `/etc` if PHP is jailed for example. I'd suggest two-pronged approach:

 - Check if `/etc/alpine-release`
 - Add configuration option `libc` with values `gnu` or `musl` perhaps (what are the differences in URL, as this would decide the actual values I suppose)?

**Comment by asgrim** [comment]
Just for reference, not as a recommendation, cURL actually has this information available in `curl_version_info_data.host`, e.g.:

```
$ php -i | grep "Host => "
Host => x86_64-pc-linux-gnu
$ docker-compose exec php-server php -i | grep "Host => "
Host => x86_64-alpine-linux-musl
$
```

However, this depends on cURL being present, and whilst practically speaking I'd expect basically all PHP installations to have cURL, it's also not a guarantee.

**Comment by cschneid** [comment]
We do have a config option: SCOUT_CORE_AGENT_TRIPLE, but it'd be nice if we had the 75% answer automatically. It doesn't have to be perfect.

**Comment by cschneid** [comment]
Also, if there's a more reliable way to tell, i'd love to know. I asked an alpine linux dev when this initially came up and they suggested the ldd approach. Which is fine, but broke in a case where `ldd` was actually a passthrough shell script or something.
