### ISSUE TITLE
Verify backtraces are captured & display in APM

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#121]
Backtrace capture is tricky with all the layers between the PHP agent and matching it up on APM's server-side with a Github name. We've had some reports of missing or mismatched 

This ticket starts as exploratory.

@asgrim - Can you verify that a new Laravel app captures backtraces when a sufficiently slow layer happens (a call to sql `pg_sleep` is my goto approach to fake this), then that data shows up in the Scout UI on the detailed trace, and that connecting it to GitHub is correct.

Potentials points to look for why backtraces may not show up:

* are they captured at all? They are typically a little slow to capture in bulk, so we attempt to only capture interesting ones. Try to ramp up the aggressiveness there?
* Marked as a span tag, named 'stack' with the correct json value (avoid double-encoding!)
* code_root is sent via the Metadata payload. It should match the root of the laravel app (the directory w/ composer.json)
* scm_subdirectory is an extra flag which adds back a prefix onto the stripped file name
* We remove "non-app" lines from the backtrace, to prevent cluttering it with libraries that aren't the customer's code. Are there any backtrace lines with clearly in-app data?

**Comment by asgrim** [comment]
- Yes, from my logging (especially with #117) it appears the stack traces are being captured and tagged, and sent to core agent
 - They are marked in a `TagSpan` named `stack`
 - `code_root` is missing from metadata, however we do have `application_root`, and its value appears to be correct (in my case: `"application_root": "\/home\/james\/workspace\/scout-apm-laravel-blog",`
 - `scm_subdirectory` is the same as `application_root` in my case
 - Only calls prefixed with the `Scout` namespace are removed at the moment. I'd advise to include framework stack traces and not forcefully remove those too though...

**Comment by asgrim** [comment]
#126 may fix this, although I can't verify as I'm still not seeing metadata in my own dashboard.

**Comment by cschneid** [comment]
See #132 for more on scm_subdirectory, but closing this as backtraces are making it all the way through to the UI.
