### ISSUE TITLE
Only set scm subdirectory if explicitly requested

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#132]
In https://github.com/scoutapp/scout-apm-php/blob/master/src/Events/Metadata.php#L112-L120 it looks like scm_subdirectory is set to the same as application root by default. Instead it should be blank by default.

The underlying issue is to match up a local file, with the location in the git repo that github knows.

```
All of this applies to any php project, but using Laravel file names as an example

A controller file, obtained by grabbing a backtrace:
/home/cschneid/Projects/blog/server/app/Http/Controllers/PublicController.php

The Laravel root is:
/home/cschneid/Projects/blog/server

The root of the git repo in this hypothetical: 
/home/cschneid/Projects/blog/
(and hypothetically has a /frontend/ subdir too with a react app in it).
```

In the case above: 

* Application Root = PHP's Root: `/home/cschneid/Projects/blog/server`
* SCM Subdirectory = just the part from the git repo root to the application root `server/`

The core agent adjusts the whole backtrace path by stripping off application root, then readding the scmsubdirectory onto the front. The PHP agent just needs to set the correct values.

Then on the server, we'd get a file name like: `server/app/Http/Controllers/PublicController.php` which matches up with Github's location of the file.

There isn't any way to auto calculate the scmsubdirectory value, and it should be blank if not set explicitly via config.

**Comment by asgrim** [comment]
Hmm, I think this comes from a differing use of terminology (possibly just in PHP circles).

In my understanding, the typical vernacular used in PHP projects is:

```
/var/www/my-app <-- application root (usually also where .git is, so also SCM directory)
    /.git
    /public (or /server, /public-html, /pub, etc.) <-- web root, where Apache/Nginx points to
        index.php
    /app
        /Controller
        /Stuff
        /Etc
    /views (or /templates, /resources, etc, but sometimes inside /app)
    /tests
    /vendor
```

I'm unclear on what paths should be application root / SCM subdirectory then, as this doesn't seem to fit with the typical structure of a PHP project? Please could you clarify meaning/intent of these wordings?

**Comment by cschneid** [comment]
The scm_subdirectory should be the path fragment from git root to application root. Note it's named *sub*directory. In your example, they are the same location, so the path from git root is nothing. This will be the case in the vast majority of cases.

Slightly changed your example to show subdirectory. Labeled below:

```
/var/www/my-app 
  /.git
  /server 
        <-- scm_subdirectory (value is only the path from git root to here, so "/server" in this case)
        <-- application root. composer.json is in this directory.

    /public (or /server, /public-html, /pub, etc.) <-- web root, or document root. Unused by Scout
        index.php
    /app
        /Controller
        /Stuff
        /Etc
    /views (or /templates, /resources, etc, but sometimes inside /app)
    /tests
    /vendor

  /client <-- some JS frontend code, unrelated to php or Scout
```

In your original example, application_root is fine, but scm_subdirectory is blank.

**Comment by asgrim** [comment]
Thanks :+1: understood now.
