### ISSUE TITLE
Verify core agent 1.2.7 fixes issue with spans before Controller

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#136]
1.2.7 of core agent is released; we'll need to bump the version pulled down, and verify that it fixes the issue we saw with payloads not being sent because there were spans (e.g. instrumentation from the `scoutapm` PHP extension) before the main Controller that core agent detects.

**Comment by cschneid** [comment]
Looking Good!

![Image 2019-12-16 at 9 42 45 AM](https://user-images.githubusercontent.com/6119/70925425-6bd1b280-1fe8-11ea-971d-b2deb00a0f36.png)
