### ISSUE TITLE
Improve check on `socket_read` for `$responseLength`

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#139]
In `\Scoutapm\Connector\SocketConnector::sendCommand`, the check on `$responseLength` should be improved:

```php
        // Read the response back and drop it. Needed for socket liveness
        $responseLength = socket_read($this->socket, 4);

        if ($responseLength === false) {
            throw Exception\FailedToSendCommand::readingResponseSizeFromSocket($message, $this->socket, $this->socketPath);
        }
```

The check should probably be something like `if ($responseLength === false || mb_strlen($responseLength) === 0)`.

Need to verify what an empty response actually signifies however; I'm assuming it's an error state.

Current reproduction method is by re-using the same socket connection to send a Register, Metadata, Request, followed by another Register (I need to verify the validity of this sequence with @cschneid)

**Comment by asgrim** [comment]
@cschneid confirmed, an empty response (e.g. from multiple `Register` payloads) is indeed an error state, so we should handle this earlier (currently, it falls through to emitting an error when calling `unpack` on the response length.

**Comment by cschneid** [comment]
More background:

The socket handler exists as a simple state machine per-connection. Connecting puts you in an "Unregistered" state, where you can do very little: ask the version of the CA you connected to, and register. Once register is called, it shifts into "Registered" state, where you can send all the request/span messages.

The expectation was that a long running web server would start up, register and then keep an open socket open (Elixir, Python both work like that), only reconnecting and reregistering if something goes wrong. PHP obviously breaks that mold a little. I think we can move registering to be tied to the connect, and not the send(), and that fixes it?
