### ISSUE TITLE
Add "extra careful" config for capturing method args from extension

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#143]
For the vast majority of customers, the args to instrumented functions like `file_get_contents` are benign and helpful to identify the call, but a few customers will end up with PII in those fields, and we need a config flag to turn off collecting the args in that case.

**Comment by asgrim** [comment]
PHP internal function calls' arguments are recorded (albeit filtered) in https://github.com/scoutapp/scout-apm-php/blob/dc13674bcb2f56e797f2674fea93777c35fe04de/src/Extension/RecordedCall.php#L91-L100 - add a configuration option to suppress this.

> Similar to https://docs.scoutapm.com/#uri_reporting

**Comment by asgrim** [comment]
Duplicate #223
