### ISSUE TITLE
Queue time mismatch between X-Request-Time scale and start time call

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#163]
The X-Request-Time header is in milliseconds, but the PHP code then does a divide by 10000, and uses microtime to compare against it, which I don't think matches up.

The current code:

* The header value comes in as milliseconds since epoch. To simplify, assume we're in 1970 and say "2".
* The code divides that number by 10000, so it's 0.0002
* Then it gets the start time as microseconds, say 3000 (3 milliseconds after epoch)
* The final value is then (3000 - 0.0002) * 1e9 = 2.999e12 nanoseconds. Which is ~50 minutes.

The expected value is:

* Header value of 2ms after epoch
* start time is 3ms after epoch
* start - header = 1ms
* convert to nanoseconds = 1e6 nanoseconds

Because of the subtraction, epoch cancels out.

https://github.com/scoutapp/scout-apm-php/blob/master/src/Events/Request/Request.php#L95-L96

https://devcenter.heroku.com/articles/http-routing#heroku-headers

**Comment by dlanderson** [comment]
I don't think this will work; I'd like to make this more robust. Take a look at [how we do it in our Python agent](https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/web_requests.py#L72). It should be easy to port over. A few things to note:

1. The headers can be any of `X-Queue-Start X-Request-Start X-QUEUE-START X-REQUEST-START x-queue-start x-request-start`
2. The value of the header can start with `t=`, but not always.
3. We can detect ambiguous values by [anchoring a start date and comparing the values](https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/web_requests.py#L149-L173).
