### ISSUE TITLE
When musl-focused core-agent is released, remove libc detection

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#166]
Since the `musl` version of core-agent should work on `glibc` based systems, we can probably remove the libc detection when it is released, and just always download the `musl` version.

**Comment by asgrim** [comment]
@cschneid assigning this to you for now, please assign it back to me when the new core-agent that is `musl`-only is released and I'll get this worked on.

**Comment by cschneid** [comment]
The musl build is the same one we've been using for Alpine linux distros, and is the triple: 

SCOUT_CORE_AGENT_TRIPLE="x86_64-unknown-linux-musl"

I think that we can just change the default triple to be that, and it'll work ok.
