### ISSUE TITLE
Memory leak on heroku web dyno

### ISSUE THREAD

**Issue by lchachurski** [scoutapp/scout-apm-php#168]
Hey guys,

We're experiencing the following issues:

<img width="1216" alt="Zrzut ekranu 2020-02-18 o 16 41 37" src="https://user-images.githubusercontent.com/3366227/74751451-90a70800-526d-11ea-8902-7fb0d935e363.png">

![Selection_094](https://user-images.githubusercontent.com/3366227/74751291-53427a80-526d-11ea-8d4e-655b36b50d65.png)

Our compser.lock the relevant part:

```
            "name": "scoutapp/scout-apm-php",
            "version": "v4.0.1",
            "source": {
                "type": "git",
                "url": "https://github.com/scoutapp/scout-apm-php.git",
                "reference": "d684eb23b045056f6cbb2bd486210769460aadda"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/scoutapp/scout-apm-php/zipball/d684eb23b045056f6cbb2bd486210769460aadda",
                "reference": "d684eb23b045056f6cbb2bd486210769460aadda",
                "shasum": ""
            },
```

If you need more data, please let me know.

**Comment by asgrim** [comment]
@lchachurski Thanks for reporting - are you instrumenting a job queue at all by any chance? Are you using just the base library (this one) or any framework additions (Laravel/Symfony)?

**Comment by lchachurski** [comment]
We're using Laravel v5.8.36 and yes there are some queues running so afaik by default we are

**Comment by asgrim** [comment]
Thanks; I will try and reproduce this some time this week. I did capture some memory leaks in #158 but clearly something else is leaking (possibly in the Laravel library itself).

**Comment by asgrim** [comment]
Hmm, could you disable the queue instrumentation to see if it makes a difference? I've tried to reproduce this using the `php-meminfo` extension to measure allocated variables, but as of 4.0.1 of the `scout-apm-php` base library, the queues are not chewing up any additional memory each iteration.

To disable queues, if you're using `.env`, add in:

```
SCOUT_DISABLED_INSTRUMENTS=["laravel_queues"]
```

If you're using a config file, open `config/scout_apm.php` and add this just before `return $config;`

```php
$config[ConfigKey::DISABLED_INSTRUMENTS] = '["laravel_queues"]';
```

**Comment by asgrim** [comment]
In my test set up, measuring allocations before (with `php-meminfo` extension), I get:

```
+----------------------------------------------------------------+-----------------+-----------------------------+
| Type                                                           | Instances Count | Cumulated Self Size (bytes) |
+----------------------------------------------------------------+-----------------+-----------------------------+
| string                                                         | 6371            | 638753                      |
| array                                                          | 1566            | 112752                      |
| bool                                                           | 1174            | 18784                       |
| null                                                           | 819             | 13104                       |
| int                                                            | 556             | 8896                        |
| Closure                                                        | 222             | 15984                       |
| Symfony\Component\Console\Input\InputOption                    | 128             | 9216                        |
| Symfony\Component\Console\Input\InputDefinition                | 82              | 5904                        |
| Symfony\Component\Console\Input\InputArgument                  | 43              | 3096                        |
| unknown                                                        | 33              | 528                         |
+----------------------------------------------------------------+-----------------+-----------------------------+
```

and after around 130 jobs being worked:

```
+----------------------------------------------------------------+-----------------+-----------------------------+
| Type                                                           | Instances Count | Cumulated Self Size (bytes) |
+----------------------------------------------------------------+-----------------+-----------------------------+
| string                                                         | 6371            | 639643                      |
| array                                                          | 1566            | 112752                      |
| bool                                                           | 1174            | 18784                       |
| null                                                           | 819             | 13104                       |
| int                                                            | 556             | 8896                        |
| Closure                                                        | 222             | 15984                       |
| Symfony\Component\Console\Input\InputOption                    | 128             | 9216                        |
| Symfony\Component\Console\Input\InputDefinition                | 82              | 5904                        |
| Symfony\Component\Console\Input\InputArgument                  | 43              | 3096                        |
| unknown                                                        | 33              | 528                         |
+----------------------------------------------------------------+-----------------+-----------------------------+
```

My test setup uses Laravel 5.8.37, which I can't imagine is much different. It may be worth using the `php-meminfo` extension to help diagnose where your memory leak is coming from (although, I wouldn't do that in prod!) - see https://github.com/BitOne/php-meminfo

Let me know if you have any further information to help us reproduce this memory issue! Thanks.

**Comment by lchachurski** [comment]
> Hmm, could you disable the queue instrumentation to see if it makes a difference?

We're on it, I'll come back to you once we gather enough data. 

Additionally, we see oddly high numbers of API response times in the panel, which may indicate long-running jobs as well.

**Comment by lchachurski** [comment]
Disabling `laravel_queues` has not solved the issue, we had an impression it helped a bit and memory was leaking slower. On the other hand, turning off `SCOUT_MONITOR=false` eliminated the issue which excludes our internal issues. 

We've also reported another issue which according to your support is connected with https://github.com/scoutapp/scout-apm-php/issues/163 Maybe somehow those are related

**Comment by asgrim** [comment]
> Additionally, the leak was detected on the core-agent rather than PHP processes
Ah interesting - @cschneid can I pass this one over to you to take a look at please, since it's core-agent related, rather than the PHP library?

**Comment by lchachurski** [comment]
We've re-enabled monitoring after updating to https://github.com/scoutapp/scout-apm-php/releases/tag/v4.1.0 and everything looks fine now. If you'd like to chase this issue please check with the prior version. 

I consider these issue solved, thanks for help once again!

**Comment by asgrim** [comment]
@lchachurski thanks for the update!

@cschneid I wonder, if the mem leak is indeed in core agent, that it might be libc version only or something, since apart from the queue time fix, switching to musl-only was the only significant change... 🤔

**Comment by lchachurski** [comment]
You're welcome! Sharing both screenshots since I've provided the latter one previously

![Selection_093](https://user-images.githubusercontent.com/3366227/76143362-181ab680-6077-11ea-9d06-ed0b3c4b63a0.png)
![Selection_094](https://user-images.githubusercontent.com/3366227/76143364-25d03c00-6077-11ea-9e1d-4669f505244e.png)

**Comment by philippe-tellier** [comment]
Sorry to post on an already closed issue, but I installed Scout yesterday on one of my Laravel app, and I get the exact same issue as @lchachurski .

The memory issue stops when I disable the Laravel queue monitoring.

I'm on Laravel v7.12.0 using `scoutapp/scout-apm-laravel` v1.5.0 with `scoutapp/scout-apm-php` v4.4.0.

Do you need any more details?
Thanks!

**Comment by asgrim** [comment]
@philippe-tellier Hi Philippe, not sure if you had any notification, but I've opened a new issue for you: scoutapp/scout-apm-laravel#61 - please could you take a look? Thanks!

**Comment by philippe-tellier** [comment]
@asgrim Hi James, yes I saw that, I'll take a like into this a little bit later today, thanks!

**Comment by asgrim** [comment]
Thanks :)
