### ISSUE TITLE
Background jobs not showing up from custom instrumentation

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout-apm-php#171]
User reporting issue getting background jobs recorded.

- I opened a Background transaction within one of our laravel commands, such as:

```
        return ScoutApm::backgroundTransaction($this->name, function() {
            return $this->laravel->call([$this, 'handle']);
        });
```

- The handle function here called dynamically runs properly.
- Later on, within the handle function, I declared a custom instrumentation as explained in the doc.

```
        ScoutApm::instrument("DataImport", "InMap.prepareData", function ($span) {
            $span->tag("instanceId", $this->settings['agencyId']);
            $this->prepareData();
        });
```

- The prepareData function runs properly but we are not able to see anything in the Scout Web UI

The app is reporting web transactions, so it seems like the core agent is running.

**Comment by asgrim** [comment]
Is ->send() being called still?

**Comment by asgrim** [comment]
@dlanderson has the customer been able to try again with a `scout-apm-php` version `4.1.0` or above to produce some logs please?

**Comment by asgrim** [comment]
I suspect this is related to #255, so closing as duplicate.
