### ISSUE TITLE
Add support for Redis

### ISSUE THREAD

**Issue by matthewchigira** [scoutapp/scout-apm-php#176]
Add support Redis, 

Other desirable features would be support for:

- [predis](https://github.com/nrk/predis)
- [phpredis](https://github.com/phpredis/phpredis)
- [Redis Clustering](https://redis.io/topics/cluster-spec)

**Comment by asgrim** [comment]
Thanks for the suggestion!

**Comment by asgrim** [comment]
This will land in the PHP extension, release 1.3.0 - see scoutapp/scout-apm-php-ext#80 and scoutapp/scout-apm-php-ext#82
