### ISSUE TITLE
Add memory delta for tracked requests

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout-apm-php#179]
Aside from N+1 insights, Scout also surfaces Memory Bloat insights for Ruby and Python. We'd like to also make this feature available for PHP.

It's pretty straight forward:
1) When a request starts, get the current RSS usage.
2) After the request finishes, get the current RSS usage and subtract the RSS value form step 1 to get the delta.
3) Tag the request with the delta value.

Refer to the python implementation [here](https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/tracked_request.py#L137)

**Comment by asgrim** [comment]
@dlanderson we already track memory usage (see https://www.github.com/scoutapp/scout-apm-php/tree/master/src%2FHelper%2FMemoryUsage.php ) - is this not working perhaps? 🤔
