### ISSUE TITLE
implement forgetCompiledOrNotExpired in ScoutViewEngineDecorator

### ISSUE THREAD

**Issue by DebbyLee** [scoutapp/scout-apm-php#293]
After upgrade to laravel/framework v9.38.0 from v9.36.2, when I ran the php artisan view:clear. I would see follow error.

  Call to undefined method Scoutapm\Laravel\View\Engine\ScoutViewEngineDecorator::forgetCompiledOrNotExpired()

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/ViewClearCommand.php:75
     71▕         }
     72▕
     73▕         $this->laravel['view.engine.resolver']
     74▕             ->resolve('blade')
  ➜  75▕             ->forgetCompiledOrNotExpired();
     76▕
     77▕         foreach ($this->files->glob("{$path}/*") as $view) {
     78▕             $this->files->delete($view);
     79▕         }

      +13 vendor frames
  14  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
  
      
Found view:clear command are calling forgetCompiledOrNotExpired now.
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Console/ViewClearCommand.php

If I manually add forgetCompiledOrNotExpired into the ScoutViewEngineDecorator file, then it would work.
Could you help to fix this?

**Comment by asgrim** [comment]
This is now fixed & released in [scoutapp/scout-apm-php:8.6.3](https://github.com/scoutapp/scout-apm-php/releases/tag/8.6.3) - thanks for the report!
