### ISSUE TITLE
Check if `version` is being used correctly in \Scoutapm\CoreAgent\Manifest

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#35]
Issue raised from discussion in https://github.com/scoutapp/scout-apm-php/pull/34#discussion_r315827680

Do we need to observe this `version` value in the manifest? Is it useful? Do we need to parse differently for different versions?

**Comment by cschneid** [comment]
1. It is not useful right now, but is part of the json.
2. It was being created incorrectly as part of the core agent release. Will be fixed today

The goal of it is to be a stable key with the "schema version" of the manifest.json file. An agent should be able to inspect it, and change behavior to support updating manifest structure (like hash format or whatever).

@dlanderson sound right?

**Comment by dlanderson** [comment]
Correct
