### ISSUE TITLE
Document development tooling usage

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#36]
We have code linters, type checkers and test runners with various options. Add a quick howto use them to `DEVELOPMENT.md`.

**Comment by asgrim** [comment]
I already summarised these in https://github.com/scoutapp/scout-apm-php/blob/master/DEVELOPMENT.md - did you want further docs on them, or were they just missed?

**Comment by cschneid** [comment]
I just missed that. Thank you!
