### ISSUE TITLE
Optimize launching of CoreAgent binary

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#37]
Currently we attempt to connect, then if that fails, launch the binary. But that means we have to open the connection on every request, and that if the binary fails launching, we'll continually  attempt to spawn it causing overhead.

A likely approach is to use the new extension to hold a persistent socket open, rather than attempting to manage it solely from PHP code.

**Comment by asgrim** [comment]
see also: scoutapp/scout-apm-php-ext#25
