### ISSUE TITLE
Loosen restriction on getallheaders package.

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#49]
Reported by a customer, we lock getallheaders down to exactly 2.0.5, but he separately has a requirement of 3.0.3. It looks like they are compatible versions, so we should just support both. 3.x was only to drop support for older (<5.6) versions of php, which is fine for us.

![Screen Shot 2019-09-03 at 4 50 05 PM](https://user-images.githubusercontent.com/6119/64207785-8ed1bf80-ce5a-11e9-9eb1-50da8b61dcd5.png)

**Comment by asgrim** [comment]
Fixed in #50
