### ISSUE TITLE
Check `scoutapm` version is reasonably up to date

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#57]
Whilst the ext should remain BC as possible, we could detect the version with `phpversion('scoutapm')` to ensure it's reasonably up to date. For example, if we are deprecating a feature in future, we could add a `deprecated` warning to error log to suggest upgrading etc., or if the ext version they're running is older than we recommend (or has perhaps security bugs), then we could notify in the logs (e.g. `notice` or `info` level)

**Comment by cschneid** [comment]
If possible, the version should be sent up w/ the app Metadata hash, so we can poke the user to upgrade in the webui as well.
