### ISSUE TITLE
Support scm_subdirectory setting

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#60]
consider different project layouts, e.g.:

```
/ <-- scm_subdirectory
  .git/
  app/ <-- app root
    src/...
    vendor/...
    composer.json
  public/
```

Also add to Metadata payload.

**Comment by dlanderson** [comment]
Just clarifying - '/' would be the scm root directory, and `app` would be the `scm_subdirectory`. In other words, the subdirectory in the SCM where we'd find the app root.
