### ISSUE TITLE
Identify a list of configuration settings in Python agent, and port them over

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#65]

**Comment by asgrim** [comment]
https://docs.scoutapm.com/#python-configuration

**Comment by asgrim** [comment]
From that list, the PHP library does not have:

 * core_agent_permissions
 * revision_sha
 * hostname

**Comment by cschneid** [comment]
* Revision SHA maps partially to #73
* Hostname maps to #70  

Permissions was a thing that was needed on some people's systems, where there was a more restrictive default umask or something.
