### ISSUE TITLE
Consider what other frameworks we can provide integration with?

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#68]
(what order?)

 - Cake
 - Symfony
 - Wordpress
 - ???

**Comment by cschneid** [comment]
Who knows how good this data is, but https://coderseye.com/best-php-frameworks-for-web-developers/ shows CodeIgnitor and Symphony as second and third place frameworks

**Comment by asgrim** [comment]
Seems reasonable; surprised me about Code Igniter tbh, the JetBrains 2019 survey sorta backs that up though too: https://www.jetbrains.com/lp/devecosystem-2019/php/

I'd suggest (in order):

 * WordPress
 * Symfony
 * Code Igniter
 * Zend Framework / Expressive
 * Cake PHP

Personally I've not looked at Code Igniter or Cake PHP for years so gonna be a bit dusty there :grinning:

**Comment by cschneid** [comment]
Wordpress is less in our wheelhouse. It has a ton of installs, but I imagine very few people are treating it as a development platform vs. as an app to use. I think I'd push it down the list, and focus on frameworks for bespoke apps.

Otherwise the list looks reasonable.

**Comment by asgrim** [comment]
OK! :)

**Comment by asgrim** [comment]
Captured in separate tickets:

 - WordPress - #97 
 - Symfony - #104 
 - Drupal - #99 
 - Magento - #98

Closing this; we can consider additional support as and when requests come up IMO.
