### ISSUE TITLE
Laravel: Move app-in-console check much earlier

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#7]
When the application is running in anything other than "serve real requests" mode, the agent should do as little as possible.

Ideally, we wouldn't even load instrumentation, but that may be hard to avoid.

But we shouldn't:
* [ ] Start or Download the Core Agent
* [ ] Log anything (or as little as possible!)
* [ ] Report any data
* [ ] Exception ever

**Comment by asgrim** [comment]
I think these requirements are captured in other tickets, so closing this off. Please do re-open if I misunderstood.
