### ISSUE TITLE
Configuration option for Hostname

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout-apm-php#70]
Config name should be: `hostname`, defaulting to nothing.

It goes into the Register command, as a `host` field, peer to `name` and `key`.

**Comment by asgrim** [comment]
@cschneid since PHP provides `gethostname()` function (which is the current value sent in the metadata), is it acceptable to have that as the default?

**Comment by cschneid** [comment]
That is a good default, but this still needs to be configurable as well.
