### ISSUE TITLE
Support HEROKU_SLUG_COMMIT environment variable

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#73]
The docs state:

> * If you are using Heroku, enable [Dyno Metadata](https://devcenter.heroku.com/articles/dyno-metadata).
  This adds a `HEROKU_SLUG_COMMIT` environment variable to your dynos, which Scout then
  associates with deploys.

I don't think this is currently supported, so presumably we should add this as a feature.

**Comment by cschneid** [comment]
Yes, this is how the obtaining the SHA for Deploy tracking works on heroku. In the [python agent](https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/config.py#L238), we look at `revision_sha` config first, then check this env var.
