### ISSUE TITLE
Demonizing failed on heroku

### ISSUE THREAD

**Issue by chabior** [scoutapp/scout-apm-php#75]
Hi,

I'm trying to use scout-apm in my Laravel project on Heroku. When the app starts, core-agent is being downloaded, but when it is starting it fails with error:

> production.DEBUG: Core Agent: /app/storage/scoutapm/scout_apm_core-latest-x86_64-unknown-linux-gnu/core-agent start --daemonize true    --socket /app/storage/scoutapm/scout_apm_core-latest-x86_64-unknown-linux-gnu/scout-agent.sock
2019-09-25T07:59:48.659112+00:00 app[web.1]: 
2019-09-25T07:59:48.665044+00:00 app[web.1]: thread 'main' panicked at 'Daemonizing failed: RedirectStreams(9)', src/main.rs:216:19

Do you have an idea why? Is it user permissions problem?

**Comment by asgrim** [comment]
Thanks for reporting this @chabior, we are investigating currently.

**Comment by Christophvh** [comment]
Got the same issue, on localhost so not heroku. Also can we tag a release for laravel 6.0 since currently need to use the master branch

**Comment by asgrim** [comment]
@Christophvh yep, I've been able to reproduce this locally, so it's not strictly related to Heroku only. Seems to be related to how pipes are handled in the latest core agent which has been recently updated. I've created PR #76 which I believe works around the issue. I'm still investigating the exact cause.
