### ISSUE TITLE
Should default CORE_AGENT_PERMISSIONS be different?

### ISSUE THREAD

**Issue by asgrim** [scoutapp/scout-apm-php#95]
https://github.com/scoutapp/scout-apm-php/pull/88#discussion_r333569343

> We used 700 in the python agent, although I haven't thought hard on if we could minimize that further.
> 
> https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/config.py#L223

Currently the setting is 0777, which is the default for `mkdir` in PHP; in #88 I added the config key, but kept the default as the existing setting.

Should this default be changed to 0700?

**Comment by cschneid** [comment]
Thoughts:

* 777 is super open, which may be an issue on shared hosting
* Dropping permissions can be awkward w/ 700, if the core agent ends up owned by root exclusively. No clue if this comes up in php-land, but I recall running into this in a python app. Of course, the whole point of the config is to handle odd cases...

**Comment by asgrim** [comment]
Theoretically, 777 shouldn't be a problem as long as it's outside the web root, but that's never a guarantee. Maybe 750?
